name: Build and deploy app to Azure Web App - api-task-project

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-net-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./Back-Proyecto

  deploy-net-app:
    runs-on: ubuntu-latest
    needs: build-net-app
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-task-project'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}

  build-react-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i
        working-directory: ./Frontend

      - name: Check code lint
        run: npm run lint
        working-directory: ./Frontend

      - name: Build
        run: npm run build
        working-directory: ./Frontend

  
